name: mynextmeal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

# PACKAGES #

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.20.2
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^2.0.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  google_sign_in: ^6.1.6
  firebase_ai: ^3.10.0
  image_picker: ^1.2.1
  firebase_storage: ^13.3.0
  camera: ^0.12.0+1
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^12.0.1
  device_info_plus: ^13.0.0
  flutter_svg: ^2.2.4
  connectivity_plus: ^7.1.1
  material_symbols_icons: ^4.2928.1
  shimmer: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/OrangeLogo.png"
  adaptive_icon_foreground: "assets/icons/Trans-Bg.png"
  adaptive_icon_background: "#FF9D00"
  adaptive_icon_foreground_inset: 28

flutter_native_splash:
  color: "#FF9D00"
  ios: true
  image: "assets/icons/Trans-Bg.png"
  android_12:
    color: "#FF9D00"

flutter:
  uses-material-design: true

  # LOCAL ASSETS #
  assets:
    - assets/logos/
    - assets/icons/

  # LOCAL FONTS #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600