// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnDzuyv9luevj4scPJ_3rLjcWka0Oq_Ss',
    appId: '1:116185447489:web:44233ecd4b93ee237f1ac0',
    messagingSenderId: '116185447489',
    projectId: 'mynextmeal-678a9',
    authDomain: 'mynextmeal-678a9.firebaseapp.com',
    storageBucket: 'mynextmeal-678a9.firebasestorage.app',
    measurementId: 'G-8WBE6H1T21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgbRCX89wb-agti3WRjBBHmHZUY3TYnAY',
    appId: '1:116185447489:android:5c0f3e013c82639d7f1ac0',
    messagingSenderId: '116185447489',
    projectId: 'mynextmeal-678a9',
    storageBucket: 'mynextmeal-678a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCggReBpAb4I_sdxRn1Tg3Bm2-gtt2go0k',
    appId: '1:116185447489:ios:afcab5acb1c755647f1ac0',
    messagingSenderId: '116185447489',
    projectId: 'mynextmeal-678a9',
    storageBucket: 'mynextmeal-678a9.firebasestorage.app',
    androidClientId: '116185447489-9fuoqpflssvpchkp883hvnlqf1qfs5e7.apps.googleusercontent.com',
    iosClientId: '116185447489-1l7udpp4vchgb7rhbc0f3gqdmpon41cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynextmeal',
  );

}